### ISSUE TITLE
Has the latest version been published to NPM yet?

### ISSUE THREAD

**Issue by darylrowland** [codemotionapps/react-native-dark-mode#11]
It looks like a version 0.0.9 is in the repo with cocoa pods support, but it doesn't appear to have been pushed to NPM yet

**Comment by DimitarNestorov** [comment]
Yes! Forgot to mark it as `latest`.
![image](https://user-images.githubusercontent.com/8790386/63439934-a743e200-c437-11e9-8f68-ccf9005c2893.png)

**Comment by darylrowland** [comment]
Ah that's better! Thanks v much for publishing this!

I am getting a slight issue with the latest version now though:

"Cannot read initialMode of undefined"

at initial-mode.ios.js:2:40

**Comment by DimitarNestorov** [comment]
Can you confirm that this issue doesn't appear on 0.0.7 too? Cause when I look at the diff https://github.com/codemotionapps/react-native-dark-mode/compare/0.0.7...0.0.9 https://diff.intrinsic.com/react-native-dark-mode/0.0.7/0.0.9 there is no difference (except an export) between the JS output of the two versions

**Comment by darylrowland** [comment]
That version seems to be causing a problem too... unless I've somehow messed up the pod installs :s
