### ISSUE TITLE
Cannot read property 'initialMode' of undefined

### ISSUE THREAD

**Issue by joe-lz** [codemotionapps/react-native-dark-mode#12]
error on import { useDarkMode } from 'react-native-dark-mode';

System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 622.64 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 8.11.2 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 25.0.2, 26.0.1, 26.0.3, 27.0.3, 28.0.0
      System Images: android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 11/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
<img width="478" alt="截屏2019-09-03上午8 40 58" src="https://user-images.githubusercontent.com/8166360/64136752-924b5380-ce26-11e9-950f-764920d63c6e.png">

**Comment by joe-lz** [comment]
# steps
yarn add react-native-dark-mode
pod install
run on iOS 13.0

**Comment by udfalkso** [comment]
Same issue here.  It seems like the podspec references a library folder which doesn't exist so the .m and .h files don't get imported?  However, adjusting that path and reinstalling leads to different errors about react lib .h files being missing.

**Comment by DimitarNestorov** [comment]
@udfalkso removing `library/` fixed it for me.
Released 0.0.10

**Comment by joe-lz** [comment]
getting this new error
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/jeodiong/Documents/myPro/rn60/ios/build/rn60/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/ReactNativeDarkMode.build/Objects-normal/x86_64/UIScreen+RNDarkModeTraitChangeListener.o /Users/jeodiong/Documents/myPro/rn60/node_modules/react-native-dark-mode/ios/UIScreen+RNDarkModeTraitChangeListener.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
<img width="833" alt="截屏2019-09-04上午8 41 24" src="https://user-images.githubusercontent.com/8166360/64217390-c9396c00-ceef-11e9-91e9-68772ec1559d.png">
/Users/jeodiong/Documents/myPro/rn60/node_modules/react-native-dark-mode/ios/UIScreen+RNDarkModeTraitChangeListener.m:55:60: Property 'currentTraitCollection' not found on object of type 'UITraitCollection'
<img width="1407" alt="截屏2019-09-04上午8 40 42" src="https://user-images.githubusercontent.com/8166360/64217358-b030bb00-ceef-11e9-80cc-ec29d7c182c4.png">

**Comment by joe-lz** [comment]
@dimitarnestorov

**Comment by joe-lz** [comment]
@udfalkso 
Is your problem solved?

**Comment by udfalkso** [comment]
Yes, clearing things out and installing and linking 0.0.10 worked for me.

**Comment by DimitarNestorov** [comment]
You need to build it using Xcode 11 in order for it to work. Using `npm run run-ios` or any other CLI command will fail.
