### ISSUE TITLE
TypeError: (0 , _react.useContext) is not a function

### ISSUE THREAD

**Issue by helloimfrog** [codemotionapps/react-native-dark-mode#15]
![image](https://user-images.githubusercontent.com/18576670/65446856-76543400-de5f-11e9-8dfd-b9458ff00107.png)

I'm using react-native 0.59.10. I've installed this library and got that error. How to fix it, guy?! :((

**Comment by DimitarNestorov** [comment]
Looks like you're running and old version of React (not React Native). React Native 0.59 uses React 16.8.3. Install that and this error should go away.
But looking at the call stack it also seems like you're trying to use this package in a class component. That means that after updating React this screen will show up:
![image](https://user-images.githubusercontent.com/8790386/65449276-51ea5e80-de43-11e9-85ae-ecf77c7fb7ab.png)
Please check out the docs to learn how to use hooks: https://reactjs.org/docs/hooks-intro.html
This library is not made to be used with class components.
