### ISSUE TITLE
A lightweight "detection only" variant

### ISSUE THREAD

**Issue by marianrick** [codemotionapps/react-native-dark-mode#16]
This is a great wrapper to support dark mode without any infrastructure. But if you already have and use theming options, this library does a little bit too much. 

Is it possible to extract `useDarkMode` and `useDarkModeContext` as the most lightweight variant of this repo? Maybe as `react-native-dark-mode-detection` or something else? This would be great and super useful.

Unfortunately, I lack the knowledge to do it myself.

**Comment by DimitarNestorov** [comment]
That would be unnecessary. Here's the most lightweight version:
```javascript
import { useDarkMode } from 'react-native-dark-mode/dist/use-dark-mode'
```
Also, this "most lightweight version" is exactly what the React Native team is doing. You can read more here: https://github.com/react-native-community/discussions-and-proposals/issues/126
And the iOS version is already in master: https://github.com/facebook/react-native/commit/63fa3f21c5ab308def450bffb22054241a8842ef
