### ISSUE TITLE
Android behaviour (pre-Android 10)

### ISSUE THREAD

**Issue by robertherber** [codemotionapps/react-native-dark-mode#17]
Android support seems to work great on Android 10, but on Android 9 the behaviour is different. Tried looking at the Android docs to get some clarity, but to no avail (apparently the UI_MODE_NIGHT flags have been available since API level 8, but Dark Mode was just introduced in Android 10? Bad docs :)

Android 10: Dark Mode support is detected, and followed as expected.

Android 9 (device Moto G7 Play): Dark Mode support is still detected as true, but neither of the system settings seems to have any effect (it's stuck on UI_MODE_NIGHT_NO ie. light mode). The settings I have available that feels logical under Display are Night Light (attempted On) and Device theme (attempted Dark).

1. Is there any fallback for pre-Android 10 that could work?
2. Otherwise I suggest everything less than Android 10 is marked as not supported.

**Comment by DimitarNestorov** [comment]
Android Auto has Night mode. This is the example app running on Android 9:
![image](https://user-images.githubusercontent.com/8790386/65609112-ebd31800-dfb7-11e9-9187-64478af18b94.png)
![image](https://user-images.githubusercontent.com/8790386/65609164-fb526100-dfb7-11e9-8014-04e6b75cd7d1.png)

**Comment by robertherber** [comment]
Yeah, and logically the "Device theme" would be accessible through some API as well. This is a screen shot of how "Device theme" works. But it doesn't seem to apply the change through this particular API..

![android_dark_mode_device_theme_1](https://user-images.githubusercontent.com/1467411/65611670-736a5800-dfb3-11e9-892d-089dacfd4b83.jpg)

But the fact remains - it doesn't seem to work on Mobile devices (at least on Moto G7 Play running Android 9) - so it should either be communicated for those cases by setting `supportsDarkMode = false` or finding a way for it to work. [From what I understand the flags used have been in Android since API level 8](https://developer.android.com/reference/android/content/res/Configuration#UI_MODE_NIGHT_YES) - which probably means `supportsDarkMode` currently will give a false positive for very many devices..

**Comment by robertherber** [comment]
Hmm, I found another setting called "Night mode" - probably the same as you've found for Android Auto. However, it's ONLY available under the Developer Settings - is it the same for you?

So as far as I understand there are four different settings related to Dark Mode on Android:
1. "Device theme" on Android 9 and lower
2. "Dark theme" on Android 10+
3. "Night mode" which is only changeable under the developer menu.
4. "Night light" which is not really related (yellowish screen) but still very easily confusable!

Listening to option 3 for this is guaranteed to confuse users in my mind. It'd be better to find a way to listen to option 2 (for Android -9). Or am I missing something here?

**Comment by AleksandrZhukov** [comment]
got the same problem on Samsung device with android 8, supportsDarkMode always set as true

is there any workaround or possibilities to fix this issue?

**Comment by DimitarNestorov** [comment]
@AleksandrZhukov check this: https://github.com/codemotionapps/react-native-dark-mode/pull/18#issuecomment-535236618

**Comment by AleksandrZhukov** [comment]
maybe this check can be done under the hood of `supportsDarkMode`?

**Comment by DimitarNestorov** [comment]
As I already said in that same comment:
> I would prefer to leave it the way it is because that's what the system reports.

> I'm interested to see the React Native team tackle it.
