### ISSUE TITLE
Error when building xcode cocoapod project

### ISSUE THREAD

**Issue by kmh0237** [codemotionapps/react-native-dark-mode#19]
I am getting an error when trying to build the project generated by pod install:

[PROJECT_DIR]/node_modules/react-native-dark-mode/ios/UIScreen+RNDarkModeTraitChangeListener.m:55:60: Property 'currentTraitCollecton' not found on object of type 'UITraitCollection'

If I take out line 55 (https://github.com/codemotionapps/react-native-dark-mode/blob/master/library/ios/UIScreen%2BRNDarkModeTraitChangeListener.m#L55) locally, the ios app builds and runs on my iPhone, but it does not update dark mode properly (always shows app in light theme).

**Comment by DimitarNestorov** [comment]
Are you using Xcode 11?

**Comment by kmh0237** [comment]
![Screen Shot 2019-09-27 at 11 10 25 AM](https://user-images.githubusercontent.com/986564/65784330-6c5c5a80-e117-11e9-95c2-bbd9c91e5191.png)

I downloaded the files to be able to run against an iOS 13 device

**Comment by DimitarNestorov** [comment]
As stated in [requirements](https://github.com/codemotionapps/react-native-dark-mode#requirements), you need Xcode 11
