### ISSUE TITLE
Using with React Navigation

### ISSUE THREAD

**Issue by davidcort** [codemotionapps/react-native-dark-mode#25]
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 3.16 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.7.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 25, 28, 29
      Build Tools: 28.0.3, 29.0.1
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1 
  npmGlobalPackages:
    react-native-cli: 2.0.1

The eventEmitter not work when the system dark-mode change in iOS

I created an file for export the value of type String (dark or light)

```
import { eventEmitter } from 'react-native-dark-mode';

const DarkMode = eventEmitter.on('currentModeChanged', newMode => newMode)
 
export default DarkMode.currentMode
```

The eventEmitter only works once when the app starts. The change in the config system is not detected.

**Comment by DimitarNestorov** [comment]
Try this:
`darkmode.js`:
```js
import { eventEmitter, initialMode } from 'react-native-dark-mode';

const DarkMode = { currentMode: initialMode }
eventEmitter.on('currentModeChanged', newMode => (DarkMode.currentMode = newMode))
 
export default DarkMode
```

`example.js`:
```js
import DarkMode from './darkmode';

console.log(DarkMode.currentMode); // This should change
```

**Comment by davidcort** [comment]
@dimitarnestorov ok i will try !!

Thanks 😄

**Comment by DimitarNestorov** [comment]
Reply to this issue if it doesn't work

**Comment by davidcort** [comment]
Not works. The currentMode not change when the system dark mode of iOS 13 change  :(

Only change when the app starts.

**Comment by DimitarNestorov** [comment]
That's really strange. I just tested out my suggestion and it seems to be working fine. I made a small repo where you should be able to clone it and run it and see it working: https://github.com/dimitarnestorov/react-native-dark-mode-event-emitter-showcase. If you can make something similar it would be the easiest way for me to help you. 
![image](https://user-images.githubusercontent.com/8790386/66963263-eda26f80-f07b-11e9-8840-148aa565cda1.png)

**Comment by manuhook** [comment]
No problem on my side, it's working fine on iOS

**Comment by davidcort** [comment]
The problem is with React Navigation. I tried chance the Back Ground color from de Stack But this use an static method. So the change of Dark Mode only works when the app starts.

**Comment by manuhook** [comment]
It's an ugly fix but you can use react-native-restart to reload automatically your app (reload when eventEmitter detect a new mode)

**Comment by DimitarNestorov** [comment]
Give me the code of your main component (the component which renders React Navigation), I'll make it work.

**Comment by davidcort** [comment]
@dimitarnestorov 

````
//darkmode.js
import { eventEmitter, initialMode } from 'react-native-dark-mode';

const DarkMode = { currentMode: initialMode }
eventEmitter.on('currentModeChanged', newMode => (DarkMode.currentMode = newMode))

export default DarkMode

//Home component
import DarkMode from './darkmode';

export default class Home extends Component {

//Header Bar configuration
static navigationOptions = {
headerTitle: ,
headerStyle: {
marginTop: Platform.OS === 'ios' ? 3 : 0
backgroundColor: DarkMode.currentMode === 'dark' ? '#000' : '#FFF' //** Here the change only works once.
}
}
````

The "static navigationOptions " is an static method for configurate the stack in react-navigation

**Comment by DimitarNestorov** [comment]
React Navigation has a theme property. Here's an example how to use it with React Native Dark Mode.
```javascript
import {useDarkModeContext} from 'react-native-dark-mode';
import {createStackNavigator} from 'react-navigation-stack';
import {createAppContainer} from 'react-navigation';

class HomeScreen extends React.Component {
  static navigationOptions = function({theme}) {
    return {
      headerStyle: {
        marginTop: Platform.OS === 'ios' ? 3 : 0,
        backgroundColor: theme === 'dark' ? '#000' : '#FFF',
      },
    };
  };
  render() {
    return (
      <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
        <Text>Home Screen</Text>
      </View>
    );
  }
}

const AppNavigator = createStackNavigator({
  Home: {
    screen: HomeScreen,
  },
});

const Container = createAppContainer(AppNavigator);
const App = () => {
  const mode = useDarkModeContext();
  return <Container theme={mode} />;
};

export default App;
```
I also updated https://github.com/dimitarnestorov/react-native-dark-mode-event-emitter-showcase so you can clone and see it in action. Also React Navigation already has a default `backgroundColor` of `headerStyle` for dark theme.

**Comment by davidcort** [comment]
Wow, very useful!! I will try this. Thanks 👍

**Comment by davidcort** [comment]
Ok i got it to work!! 🗡 

```
import { eventEmitter, initialMode } from 'react-native-dark-mode';
import {StatusBar} from 'react-native';

export default class App extends Component {

constructor(){
super()

 this.state = {
systemDarkMode: initialMode
}

 eventEmitter.on('currentModeChanged', newMode => this.setState({ systemDarkMode: newMode }))

}

render(){
    const {systemDarkMode} = this.state

    return(
      <View style={{ flex: 1 }}>

        <StatusBar barStyle={systemDarkMode === 'dark' ? 'light-content' : 'dark-content'} />
          
            <AppContainer   
                theme={systemDarkMode} //** if the theme of react-navigation is 'light' show the status bar with background color in white, if is dark so change the background color to black.
            />

      </View>
    )
    
  }

}
```

Thanks to everyone for your help and for this plugin 👍
