### ISSUE TITLE
eventEmitter constantly called on android

### ISSUE THREAD

**Issue by manuhook** [codemotionapps/react-native-dark-mode#33]
Hi!
With the release 0.2.0 the eventEmitter is constantly fired on Android (Tested on Android 10 and 8.1)
It was not the case on the precedent release (<0.2).
Thank you !

**Comment by DimitarNestorov** [comment]
0.2.1-rc.0 released

**Comment by vforvasile** [comment]
This was fixed for Android only, it happens on iOS as well, 
using 
```
"react-native-dark-mode": "0.2.1",
"react-native": "0.61.4"
```
![Screen Shot 2019-11-15 at 17 06 25](https://user-images.githubusercontent.com/9382283/68953331-5dfef680-07ca-11ea-904f-836d701870b8.png)

**Comment by DimitarNestorov** [comment]
Are you calling eventEmitter.off?

**Comment by matheusbaumgart** [comment]
I'm also having this issue on iOS and I'm not calling eventEmitter.off because I haven't manually created one. I'm just using the "high level APIs". @dimitarnestorov please advise.

**Comment by DimitarNestorov** [comment]
@matheusbaumgart Did you wrap your application with `<DarkModeProvider>`?
