### ISSUE TITLE
Text style inside of textInput element does not update when mode changes

### ISSUE THREAD

**Issue by nestedJSObject** [codemotionapps/react-native-dark-mode#34]
With DynamicStyleSheet, DynamicValue, useDynamicStyleSheet, the text entered in a textInput element does not change style when the mode changes. All the text in the textInput element needs to be deleted first and then the style updates.

**Comment by DimitarNestorov** [comment]
I need more info, I wasn't able to reproduce the issue. Here's what I tried:

```javascript
import React, {useState} from 'react';
import {SafeAreaView, TextInput} from 'react-native';
import {
  DynamicStyleSheet,
  DynamicValue,
  useDynamicStyleSheet,
} from 'react-native-dark-mode';

const dynamicStyleSheet = new DynamicStyleSheet({
  safeAreaView: {
    flex: 1,
    alignItems: 'stretch',
    backgroundColor: new DynamicValue('white', 'black'),
  },
  input: {
    backgroundColor: new DynamicValue('#DDD', '#333'),
    color: new DynamicValue('black', 'white'),
  },
});

const App = () => {
  const styles = useDynamicStyleSheet(dynamicStyleSheet);
  const [value, setValue] = useState('');
  return (
    <SafeAreaView style={styles.safeAreaView}>
      <TextInput style={styles.input} value={value} onChangeText={setValue} />
    </SafeAreaView>
  );
};

export default App;
```

![Kapture 2019-10-19 at 20 41 47](https://user-images.githubusercontent.com/8790386/67149222-4a3aa000-f2b1-11e9-83b3-6921e759bda2.gif)
![Kapture 2019-10-19 at 20 50 00](https://user-images.githubusercontent.com/8790386/67149277-1b70f980-f2b2-11e9-858b-15a7aa2e926f.gif)

**Comment by nestedJSObject** [comment]
I see that it works when you add the value / onChangeText props -- without them, I was experiencing the problem. Thank you!
