### ISSUE TITLE
Fatal Exception: com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'initialMode' of null, js engine: hermes, stack:

### ISSUE THREAD

**Issue by jbohman** [codemotionapps/react-native-dark-mode#35]
I get this on Android but not on iOS. 

Library version: 0.2.0
React Native version: 0.61.2

Only code I use is:

```
import { useDarkMode } from 'react-native-dark-mode';
const isDarkMode = useDarkMode();
```

![image](https://user-images.githubusercontent.com/95589/67318741-28892500-f50c-11e9-9e1a-a78459e9678f.png)

**Comment by DimitarNestorov** [comment]
Try this:
![image](https://user-images.githubusercontent.com/8790386/67319079-1d86c280-f515-11e9-84d7-9a78a1121942.png)
Or close Android Studio and open it again.

**Comment by ex3ndr** [comment]
Didn't helped me too

**Comment by DimitarNestorov** [comment]
Run `react-native info` and paste the output

**Comment by DimitarNestorov** [comment]
Try restarting the packager.
Also try deleting the app and installing it again.

**Comment by iOlivier** [comment]
I have the same issue. 
You can find a screenshot of the issue and my `react-native info` output below:

![Screenshot 2019-10-28 at 15 14 17](https://user-images.githubusercontent.com/12254953/67685633-babe7c80-f995-11e9-8f07-d446382c855f.png)

```
info
  React Native Environment Info:
    System:
      OS: macOS 10.15
      CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 704.97 MB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v10.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-24 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native: 0.59.9
```

**Comment by DimitarNestorov** [comment]
@iOlivier run `pod install` again. Then in Xcode do this:
![image](https://user-images.githubusercontent.com/8790386/67686084-d4b08d00-f99e-11e9-862b-1697344a7573.png)
And build and run again.

**Comment by iOlivier** [comment]
@dimitarnestorov 
This did the trick for me. Thank you! 😀

I also updated my global react-native version to 0.59.9 just before I posted in this thread. Maybe this also helped.

**Comment by orlowang** [comment]
try clear & rebuild, android 10 still error
```
System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Memory: 25.68 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 26, 28
      Build Tools: 23.0.1, 25.0.1, 25.0.2, 26.0.2, 28.0.3
      System Images: android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.61.3 => 0.61.3
```

**Comment by baierjak** [comment]
Any news on this? I am getting the same error on emulator Android 10. Clean and rebuild didnt help

**Comment by chagai95** [comment]
getting the same error, when adding webrtc code that works on the browser... found this issue by googling the error, anyone understand it?
