### ISSUE TITLE
Fatal Exception: com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'initialMode' of null, js engine: hermes, stack

### ISSUE THREAD

**Issue by BruceThomson** [codemotionapps/react-native-dark-mode#38]
Working on iOS Android has the following error on startup:
Fatal Exception: com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'initialMode' of null, js engine: hermes, stack

I have deleted the app and reinstalled it. Restarted the metro bundler, cleaned the iOS Build Folder and removed and reinstalled the pods. Still not working on Android. 

react-native info:
System:
    OS: macOS 10.15
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 23.81 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.3.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.0, 28.0.3, 29.0.0
      System Images: android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2/11B41 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: ^0.61.2 => 0.61.2
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

**Comment by DimitarNestorov** [comment]
Clone this: https://github.com/dimitarnestorov/test-react-native-dark-mode
Build and run and tell me what you get this time

**Comment by martin-przystalka** [comment]
Same issue here.

@dimitarnestorov I build my app with your branch and I got:
`[error][tid:com.facebook.react.JavaScript] Error: Requiring unknown module "1058". If you are sure the module exists, try restarting Metro. You may also want to run yarn or npm install.`

**Comment by DimitarNestorov** [comment]
@martin-przystalka iOS or Android?
Also are you sure you're not running the packager for your app? https://stackoverflow.com/a/49660444/882847

**Comment by ghost** [comment]
I am getting the same error on Android emulator running android 10.

**Comment by DimitarNestorov** [comment]
@kheraprabhat Clone this: dimitarnestorov/test-react-native-dark-mode
Build and run and tell me what you get this time

**Comment by ghost** [comment]
@dimitarnestorov It is not working as well. It is giving me an error that useDarkMode is not defined

**Comment by DimitarNestorov** [comment]
@kheraprabhat What error?
Give me a screenshot, copy paste the stack trace?

**Comment by ghost** [comment]
@dimitarnestorov 
<img width="401" alt="Screen Shot 2019-11-25 at 9 48 04 PM" src="https://user-images.githubusercontent.com/2478868/69691516-35fd8480-1134-11ea-9802-a4811847270d.png">

**Comment by DimitarNestorov** [comment]
When I search for `ThemeProvider` in `node_modules` or the project no results are shown.
Files `hoc.js` and `ComponentWrapper.js` are also missing.
Did you modify the repo before running? Can you upload a zip of your cloned repo when you try to run the app (I need the node_modules folder included)?
