### ISSUE TITLE
Add new func to get current dark mode state

### ISSUE THREAD

**Issue by rangav** [codemotionapps/react-native-dark-mode#39]
Hi Thanks for the library, very useful.

The eventemitter wont fire when the app is in background and user has changed darkmode. it would be  better to add a new function to get dark mode state.

Please let me know if its possible

Sample example for iOS:
```
RCT_EXPORT_METHOD(getCurrentMode:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
{
  if (@available(iOS 13.0, *)) {
      if (UITraitCollection.currentTraitCollection.userInterfaceStyle == UIUserInterfaceStyleDark) {
        resolve(@"dark");
      }
      else {
        resolve(@"light");
      }
  }else{
    resolve(@"light");
  }
}
```

**Comment by DimitarNestorov** [comment]
I can't reproduce this issue.
Can you give me an example repo and steps to reproduce?

**Comment by rangav** [comment]
Here are steps:
1. Use goes to home screen from app
2. Changes from light to dark
3. Opens the app again

Now how can app know the new darkmode state without hooks?

**Comment by rangav** [comment]
Sorry my poor testing 

actually eventEmitter event is firing when app coming background to active. No Changes needed we can close the issue
