### ISSUE TITLE
Cocoapods Support

### ISSUE THREAD

**Issue by HParis** [codemotionapps/react-native-dark-mode#4]
Hi, I have used cocoapods to import the react-native. So can you support this feature?

**Comment by Xetoxyc** [comment]
i have just made a new pull request with my working cocoapods spec file. 

You can just grab the file and add it into your 
`node_modules/react-native-dark-mode`
 directory. 

After you just have to add 
`pod 'ReactNativeDarkMode', :podspec => '../node_modules/react-native-dark-mode/ReactNativeDarkMode.podspec'`
 into your Podspec and run 
`pod install`
 once.

**Comment by DimitarNestorov** [comment]
I just merged #5 and released 0.0.8. Hopefully this does the job for you guys. Can't upgrade to 0.60 yet, so I won't be supporting it for now. PRs welcome.

**Comment by robertherber** [comment]
Cocoapods install failed for me - so I added #6 to make it install properly.

**Comment by Xetoxyc** [comment]
> Cocoapods install failed for me - so I added #6 to make it install properly.

maybe not compatible with some versions of cocoapods. Worked well for me and my colleague.

**Comment by DimitarNestorov** [comment]
0.0.9 (#8) is out
