### ISSUE TITLE
MAXListenerExceededWarning

### ISSUE THREAD

**Issue by emachta** [codemotionapps/react-native-dark-mode#41]
This repo should make it more clear that in order to avoid any warnings due to memory leaks from too many event emitter listeners, the user needs to add a context api <DarkModeProvider> around the whole app, which will only make it use one event emitter. I wasn't using the provider, only the dynamicvalue and dynamicstylesheet components, but I didn't know it was adding so many event emitters to my app.

Warning:
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 currentModeChanged listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by DimitarNestorov** [comment]
`README.md`:
> It is recommended to wrap your application in a `DarkModeProvider` without a mode prop to observe a performance improvement.

Some people don't need to wrap their apps and that's why I haven't mentioned it more explicitly.

**Comment by chrise86** [comment]
@dimitarnestorov how do you use the context value in the child components' stylesheets then?

**Comment by DimitarNestorov** [comment]
@chrise86 the context has a default value.

**Comment by chrise86** [comment]
@dimitarnestorov wow that was a quick response, thanks! Got it, thanks!
