### ISSUE TITLE
ios giving error while building.

### ISSUE THREAD

**Issue by reactdevrocks** [codemotionapps/react-native-dark-mode#42]
Property 'currentTraitCollection' not found on object of type 'UITraitCollection'.

**Comment by DimitarNestorov** [comment]
I will need a more information to help you like a screenshot or a stack trace

**Comment by DimitarNestorov** [comment]
Is it similar to this: https://github.com/codemotionapps/react-native-dark-mode/issues/12#issuecomment-527692688?
Which version of Xcode do you have installed?

**Comment by mauleb** [comment]
@dimitarnestorov I'll jump in as I just got this error as well. 

>Xcode 10.3
Build version 10G8

**Comment by DimitarNestorov** [comment]
@mauleb You need Xcode 11: https://github.com/codemotionapps/react-native-dark-mode#requirements

**Comment by mauleb** [comment]
Thanks for the quick response
