### ISSUE TITLE
Build Error in iOS

### ISSUE THREAD

**Issue by annjawn** [codemotionapps/react-native-dark-mode#43]
I am getting this error when trying to import from `react-native-dark-mode`. I've installed it using the instructions as -

```
$ npm install react-native-dark-mode
$ cd ios && pod install
```
I am using expo with RN, but is there any additional steps I am missing, can't seem to find anything in the documentation.

<img width="385" alt="Screen Shot 2020-01-11 at 9 03 54 PM" src="https://user-images.githubusercontent.com/26977294/72214409-205ed700-34b6-11ea-8dd9-bd2f2e21147a.png">

**Comment by DimitarNestorov** [comment]
This module doesn't work with Expo. Use this instead: https://github.com/expo/react-native-appearance

**Comment by annjawn** [comment]
Yup i realized it after installing. I am using react-native-appearance now. Thanks for the reply.
