### ISSUE TITLE
Set dark mode programatically

### ISSUE THREAD

**Issue by boypanjaitan16** [codemotionapps/react-native-dark-mode#44]
sorry, but any idea how to set dark mode programatically, I mean to all over the screen in app

**Comment by DimitarNestorov** [comment]
Wrap your app inside a `DarkModeProvider` and set the desired mode prop:
```javascript
function App() {
	return (
		<DarkModeProvider mode="dark">
			{/* ... */}
		</DarkModeProvider>
	)
}
```

https://github.com/codemotionapps/react-native-dark-mode#darkmodeprovider

**Comment by boypanjaitan16** [comment]
I did, but nothing seems happen

**Comment by DimitarNestorov** [comment]
I will need a minimal reproduction example to help you out.
