### ISSUE TITLE
How can I change mode manually in app (like hook)

### ISSUE THREAD

**Issue by magneutron** [codemotionapps/react-native-dark-mode#51]
Can I change to dark or light mode manually in App?

**Comment by DimitarNestorov** [comment]
Yes: https://github.com/codemotionapps/react-native-dark-mode#darkmodeprovider

> #### `DarkModeProvider`
> 
> Allows you to set a specific mode for children.
> 
> ```javascript
> import { DarkModeProvider } from 'react-native-dark-mode'
> 
> function MyScreen() {
> 	return (
> 		<>
> 			{/* will be rendered using dark theme */}
> 			<DarkModeProvider mode="dark">
> 				<Component />
> 			</DarkModeProvider>
> 
> 			{/* will be rendered using light theme */}
> 			<DarkModeProvider mode="light">
> 				<Component />
> 			</DarkModeProvider>
> 
> 			{/* will be rendered using current theme */}
> 			<Component />
> 		</>
> 	)
> }
> ```
