### ISSUE TITLE
How did i use this plugin in public, when i use class

### ISSUE THREAD

**Issue by GuiltyKirito** [codemotionapps/react-native-dark-mode#53]
- iOS:13
How did i use this plugin in public, when i use class and i don't know how to get initialMode activity when i change iOS theme mode it's doesn't change

**Comment by DimitarNestorov** [comment]
To use this module with classes see this: https://github.com/codemotionapps/react-native-dark-mode/issues/27#issuecomment-559917799

**Comment by GuiltyKirito** [comment]
> To use this module with classes see this: [#27 (comment)](https://github.com/codemotionapps/react-native-dark-mode/issues/27#issuecomment-559917799)

Thanks for your help 💗XDDDD
