### ISSUE TITLE
TypeError: (0 , _react.useContext) is not a function

### ISSUE THREAD

**Issue by caijiami** [codemotionapps/react-native-dark-mode#55]
"react": "16.6.3",
"react-native": "0.58.6",
hope to get help

**Comment by DimitarNestorov** [comment]
Hooks were introduced with React 16.8. Also this module requires React Native 0.59.9 to support iOS.

**Comment by caijiami** [comment]
Is there a limit to the version of android

**Comment by DimitarNestorov** [comment]
I don't know
