### ISSUE TITLE
iOS 13.4.1 update causes all iOS versions to no longer recognize first dark theme change

### ISSUE THREAD

**Issue by kmh0237** [codemotionapps/react-native-dark-mode#57]
In iOS, both event emitter seems to no longer recognize the first change from dark to light theme when we tested it.  We think it is something changed on the apple/iOS side, since we hadn't changed anything in our code and it all of a sudden stopped.  From our testing, in 13.3 subsequent changes seem to register, but in 13.4.1 it doesn't recognize changes.

**Comment by DimitarNestorov** [comment]
Does it also happen on Simulator? I don't have devices on 13.4.1 to test with.

**Comment by kmh0237** [comment]
We tested on physical devices on an app that's already been deployed, as well as running it locally through xcode on a physical device.  Unfortunately we haven't been able to run our solution with emulator yet due to unrelated issues.  It did work on physical devices as of a few days ago, so that's why I suspect an apple/iOS change since it's literally the same source.  It should also be reproducible on iOS 13.3 btw

**Comment by DimitarNestorov** [comment]
What about iOS 13.5 beta? Can you run it on that version? I don't have devices running iOS 13.3.

**Comment by kmh0237** [comment]
We just finished testing on a physical device with 13.5 beta.  It looks like the issue occurs on that version as well, so you should be good to test it out using 13.5 beta

**Comment by DimitarNestorov** [comment]
I don't have devices running iOS 13.5 beta. I was just hoping that it was a bug that got fixed. I can only help you if you create a small example app where the issue occurs on Simulator.

**Comment by kmh0237** [comment]
Ok, will probably have an example here in a few days or longer, working on other things atm.  Thanks for the quick response!

**Comment by DimitarNestorov** [comment]
I also might be getting a device on some of those versions next week. Can you post a link of your app if it's not private so that I can check it out?

**Comment by kmh0237** [comment]
It is private, sorry!

**Comment by DimitarNestorov** [comment]
Can't reproduce on an iOS 13.3.1 device. I'm still gonna need a small example app, preferably reproducible on Simulator.
