### ISSUE TITLE
android: app not oppening after install

### ISSUE THREAD

**Issue by giovaniif** [codemotionapps/react-native-dark-mode#58]
Hello Guys!
So, I was trying to use this lib and ran into a bug, when I try to build the app.
The app is installed on the phone but, it just doesn't open. I just keep getting this error:
"Application keeps stopping"

<img src="https://media.giphy.com/media/lT9PWZDOsm9KdD5k8P/giphy.gif" />

The lib was installed using yarn.
After following the docs, I ran ```yarn android```
The app was installed but didn't even open, it just finishes the installation then closes.
Even starting the metro bundler manually ```yarn start```, the error keeps happening.

**Comment by DimitarNestorov** [comment]
You need to debug it using Android Studio and paste the errors from Logcat. Have you also considered updating to React Native 0.62? It has dark mode support built in.

**Comment by giovaniif** [comment]
So, I have uninstalled the lib and used the react native default module, it works fine. Thanks!
