### ISSUE TITLE
TypeError: null is not an object (evaluating '_nativeModule.NativeModule.initialMode')

### ISSUE THREAD

**Issue by wangpeitao123** [codemotionapps/react-native-dark-mode#59]
TypeError: null is not an object (evaluating '_nativeModule.NativeModule.initialMode')

<global>
    initial-mode.js:2:27
loadModuleImplementation
    require.js:321:11
<global>
    dark-mode-event-emitter.js:2
loadModuleImplementation
    require.js:321:11
<global>
    event-emitter.js:2
loadModuleImplementation
    require.js:321:11
<global>
    context.js:2
loadModuleImplementation
    require.js:321:11
<global>
    index.js:1
loadModuleImplementation
    require.js:321:11
<global>
    IMToolBar.js:16
loadModuleImplementation
    require.js:321:11
<global>
    index.js:3
loadModuleImplementation
    require.js:321:11
guardedLoadModule
    require.js:201:44
global code
    index.bundle?platform=ios&dev=true&minify=false:110961:3

**Comment by DimitarNestorov** [comment]
What version of React Native are you running?

**Comment by wangpeitao123** [comment]
My React Native version is 0.62.2.

**Comment by DimitarNestorov** [comment]
Dark mode is natively supported by React Native 0.62:
https://reactnative.dev/docs/appearance

**Comment by wangpeitao123** [comment]
ok,thanks！
