### ISSUE TITLE
useDarkModeContext context.js:28:31

### ISSUE THREAD

**Issue by fanzhiri** [codemotionapps/react-native-dark-mode#61]
i have no idea where was go wrong .
i got a red Page , showing "Invariant Violation: Invalid hook call "

**Comment by DimitarNestorov** [comment]
What version of React Native are you using?

**Comment by fanzhiri** [comment]
> What version of React Native are you using?

"react": "16.8.6",
"react-native": "0.60.5",

**Comment by DimitarNestorov** [comment]
Did you call the function inside a functional component?

**Comment by fanzhiri** [comment]
> Did you call the function inside a functional component?

I don't have functional component .

myComponent extends Component

how to use react-native-dark-mode in myComponent ?

**Comment by DimitarNestorov** [comment]
The high level APIs are hooks which can only be called in functional
components. Read more about hooks here:
https://reactjs.org/docs/hooks-intro.html
If you don’t want to use them you can try the low level APIs mentioned at
the bottom of the README
