### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by robertherber** [codemotionapps/react-native-dark-mode#9]
As per #7 

One point that could be discussed is whether we should add support for the third preference "no-preference" that applies to the web. Right now this Pull Request adapts to the previous structure of react-native-dark-mode. Not sure how it works in Android - if this would make sense in the bigger picture?

**Comment by DimitarNestorov** [comment]
https://github.com/expo/react-native-appearance has web support

**Comment by crutchcorn** [comment]
I currently have a problem that I'd like to solve by adding Web Support: I would like to be able to run my React Native app (which will _not_ be coming to the web) in a Storybooks instance that _does_ run on the web. This makes it much easier to collaborate between my designer and I as I only need to host a web instance for our shared component system without having to provide an APK. However, we make extensive use of dark mode to provide theme values, so none of my components will work without this. 

Would you be open to receiving a PR that enables full functionality with the web if I were to do so?

**Comment by DimitarNestorov** [comment]
Dark mode is natively supported by React Native 0.62:
https://reactnative.dev/docs/appearance
react-native-web doesn’t seem to support it yet. You can open an issue
there or you can use, as suggested above, react-native-appearance just for
your web target until react-native-web implements support.

**Comment by crutchcorn** [comment]
But I don't use this package simply due to it's support for detecting if an item is in dark mode or not: 

I primarily use it because of it's `StyleSheet.create` alternative and the `DynamicValue` support. I've built an entire theme around this idea and have ~10k LOC built on top of this package. 

I know there are other options, but none provide the functionality or convinience I'm looking for.

**Comment by DimitarNestorov** [comment]
In about a week when we upgrade our app at the company to React Native 0.62
I will be deprecating this package. The DynamicStyleSheet and DynamicValue
classes will be moved to a new package.

**Comment by crutchcorn** [comment]
Gotcha, thanks for the info. I'll keep my eye out for that, then :)

**Comment by DimitarNestorov** [comment]
@crutchcorn I just released [react-native-dynamic](https://www.npmjs.com/package/react-native-dynamic)@1.0.0-rc.3 and it looks good. I made it possible for an easy switch, if you're not using any low level APIs you should be able to just find and replace all occurrences of `react-native-dark-mode` with `react-native-dynamic`. But keep in mind that I am planning on removing `useDynamicStyleSheet` (replaced by `useDynamicValue`) and renaming `DarkModeContext` to `ColorSchemeContext`, `DarkModeProvider` to `ColorSchemeProvider`, and `useDarkModeContext` to `useColorSchemeContext`. When will I release 2.0.0? Probably never. If you find any bugs open them an issue in https://github.com/codemotionapps/react-native-dynamic.
